spring.application.name=vinyl-record-collection-tracker

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET_KEY}

resend.api.key=${RESEND_API_KEY}
resend.from.address=${RESEND_FROM_ADDRESS}

app.frontend.url=${FRONTEND_URL:http://localhost:5173}

discogs.token=${DISCOGS_TOKEN}
discogs.base-url=https://api.discogs.com

server.servlet.session.cookie.same-site=lax